---
title: "Merging Data"
output: html_document
---

```{r}
library(tidyverse)
library(conflicted)
library(readxl)

```

```{r}
AirQuality <- read_csv(paste0("~/Documents/PROJECT-CLONES/Data-Storage/",
                              "AirQualityData/indices_QA_commune_IDF_2017.csv"))

transport <- read_excel(paste0("~/Documents/PROJECT-CLONES/Data-Storage/",
                               "AirQualityData/transport.xlsx"),
                        col_types = "text")

Weather <- read_delim(paste0("~/Documents/PROJECT-CLONES/Data-Storage/",
                             "AirQualityData/Q_75_previous-1950-2024_RR-T-Vent.csv"), 
                      delim = ";",
                      escape_double = FALSE,
                      trim_ws = TRUE)

```


```{r}
Weather <- Weather |> 
  mutate_at(vars(AAAAMMJJ),
            function(x){
              
              Year = str_sub(x,
                             start = 1,
                             end   = 4)
              
              Month = str_sub(x, 
                              start = 5,
                              end   = 6)
              Day = str_sub(x,
                            start = 7,
                            end   = 8)
              
              x = paste0(Year, "-", Month, "-", Day)
              
              x = as.Date(x, format = "%Y-%m-%d")
              
            }) |> 
  dplyr::filter(between(AAAAMMJJ,
                        as.Date("2017-01-01",
                                format = "%Y-%m-%d"),
                        as.Date("2017-12-31",
                                format = "%Y-%m-%d")))

temp <- Weather |> 
  select(where(~any(!is.na(.))))

```


```{r}
transport <- transport |> 
  mutate_at(vars(Autoroute:`Autres routes`),
            function(x){
              
              x = as.character(x)
              
              x = replace_na(x, "0")
              
              x = as.numeric(x)
              
            }) |> 
  rename_at(vars(Autoroute:`Autres routes`),
            function(x){
              
              x = tolower(x)
              
              x = gsub(" ", "_", x)
              
              x = paste0("transport_", x)
            
              
            })

```

```{r}
AirQuality <- AirQuality |> 
  dplyr::filter(!ninsee %in% c("0",
                               "75",
                               "77",
                               "78",
                               "91",
                               "92",
                               "93",
                               "94",
                               "95")) |> 
  mutate(ninsee = as.character(ninsee)) |> 
  left_join(transport,
            by = "ninsee")

rm(list = ls(pattern = "transport"))
```